from typing import Protocol, List, Optional

class EmbeddingService(Protocol):
    def embed(self, text: str) -> List[float]: ...

class DocumentStore(Protocol):
    def add(self, doc_id: int, vector: List[float], text: str) -> bool: ...
    def search(self, vector: List[float], query: str, limit: int = 2) -> List[str]: ...
    def get_count(self) -> int: ...
    def is_ready(self) -> bool: ...