from typing import Protocol, List
from src.domain.models import Document

class DocumentStore(Protocol):
    def add(self, document: Document) -> bool: ...
    def search(self, vector: List[float], query: str, limit: int = 2) -> List[str]: ...
    def get_count(self) -> int: ...
    def is_ready(self) -> bool: ...
